version: '3.8'

services:

  jenkins:

    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/wildan/assignment/Jenkins/jenkins-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
